# Generated by Django 4.2.1 on 2023-05-19 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSRController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.BooleanField(default=False)),
                ('autoName', models.BooleanField(default=True)),
                ('name', models.CharField(default='set Name', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=32)),
                ('desc', models.CharField(blank=True, default='', max_length=64)),
                ('ipaddress', models.CharField(blank=True, default='', max_length=15)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=64, verbose_name='Manufacturer')),
                ('manufactureType', models.CharField(blank=True, default='', max_length=64, verbose_name='Type')),
                ('photo', models.ImageField(blank=True, default='', upload_to='pics/controller')),
            ],
            options={
                'verbose_name': 'C1 Controller',
                'verbose_name_plural': 'C1 Controllers',
            },
        ),
        migrations.CreateModel(
            name='MSRDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.BooleanField(default=False)),
                ('autoName', models.BooleanField(default=True)),
                ('name', models.CharField(default='set Name', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=32)),
                ('devFunction', models.CharField(blank=True, default='', max_length=64, verbose_name='Function')),
                ('desc', models.CharField(blank=True, default='', max_length=64)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=64, verbose_name='Manufacturer')),
                ('manufactureType', models.CharField(blank=True, default='', max_length=64, verbose_name='Type')),
                ('photo', models.FileField(blank=True, default='', upload_to='pics/device', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
            ],
            options={
                'verbose_name': 'B2 Device',
                'verbose_name_plural': 'B2 Devices',
            },
        ),
        migrations.CreateModel(
            name='MSRField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.BooleanField(default=False)),
                ('autoName', models.BooleanField(default=True)),
                ('name', models.CharField(default='set Name', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=128)),
                ('photo', models.ImageField(blank=True, default='', upload_to='pics')),
                ('creator', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Field', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'A2 Field',
                'verbose_name_plural': 'A2 Fields',
            },
        ),
        migrations.CreateModel(
            name='MSRSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_type', models.CharField(choices=[('000', 'not defined'), ('001', 'Sensor'), ('002', 'Pump'), ('003', 'Valve 2-way'), ('004', 'Valve 3-way')], default='000', max_length=3)),
                ('name', models.CharField(default='symbols name', max_length=128)),
                ('symbol', models.FileField(blank=True, default='', upload_to='pics/symbol', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('device', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Symbol', to='MSR.msrdevice', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'B2.2 Symbol',
                'verbose_name_plural': 'B2.2 Symbols',
            },
        ),
        migrations.CreateModel(
            name='MSRSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.BooleanField(default=False)),
                ('autoName', models.BooleanField(default=True)),
                ('name', models.CharField(default='set Name', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=32)),
                ('desc', models.CharField(blank=True, default='', max_length=64)),
                ('field', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Site', to='MSR.msrfield', verbose_name='Field')),
            ],
            options={
                'verbose_name': 'B1 Site',
                'verbose_name_plural': 'B1 Sites',
            },
        ),
        migrations.CreateModel(
            name='MSRProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='set Name', max_length=128)),
                ('project_ID', models.CharField(max_length=32)),
                ('photo', models.ImageField(blank=True, default='', upload_to='pics')),
                ('creator', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('users', models.ManyToManyField(to='auth.group')),
            ],
            options={
                'verbose_name': 'A1 Project',
                'verbose_name_plural': 'A1 Projects',
            },
        ),
        migrations.CreateModel(
            name='MSRModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.BooleanField(default=False)),
                ('autoName', models.BooleanField(default=True)),
                ('name', models.CharField(default='set Name', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=32)),
                ('slot', models.IntegerField(blank=True, default=0)),
                ('desc', models.CharField(blank=True, default='', max_length=64)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=64, verbose_name='Manufacturer')),
                ('manufactureType', models.CharField(blank=True, default='', max_length=64, verbose_name='Type')),
                ('photo', models.ImageField(blank=True, default='', upload_to='pics/module')),
                ('controller', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Module', to='MSR.msrcontroller', verbose_name='Controller')),
            ],
            options={
                'verbose_name': 'C2 Module',
                'verbose_name_plural': 'C2 Modules',
            },
        ),
        migrations.CreateModel(
            name='MSRIOFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.BooleanField(default=False)),
                ('autoName', models.BooleanField(default=True)),
                ('name', models.CharField(default='set Name', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.IntegerField(blank=True, default=0)),
                ('objType', models.CharField(default='None', max_length=16)),
                ('comment', models.CharField(blank=True, default='', max_length=64)),
                ('objFunction', models.CharField(default='None', max_length=16)),
                ('hardware', models.BooleanField(blank=True, default=True)),
                ('desc', models.CharField(blank=True, default='', max_length=64)),
                ('control', models.CharField(blank=True, default='', max_length=8, verbose_name='logic-parameter')),
                ('value', models.IntegerField(blank=True, default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=8)),
                ('device', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IOFunction_D', to='MSR.msrdevice', verbose_name='Device')),
                ('msrModule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IOFunction_M', to='MSR.msrmodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'D IOFunction',
                'verbose_name_plural': 'D IOFunctions',
            },
        ),
        migrations.AddField(
            model_name='msrfield',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Field', to='MSR.msrproject', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='msrdevice',
            name='site',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Device', to='MSR.msrsite', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='msrcontroller',
            name='field',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Controller', to='MSR.msrfield', verbose_name='C_Field'),
        ),
        migrations.CreateModel(
            name='MSRCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.BooleanField(default=False)),
                ('autoName', models.BooleanField(default=True)),
                ('name', models.CharField(default='set Name', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=32)),
                ('page', models.IntegerField(blank=True, default=0, verbose_name='Page')),
                ('page_path', models.IntegerField(blank=True, default=0, verbose_name='Page-Path')),
                ('description', models.CharField(blank=True, default='', max_length=64, verbose_name='Description')),
                ('crossSection', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Cross Section')),
                ('device', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cable', to='MSR.msrdevice', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'B2.1 Cable',
                'verbose_name_plural': 'B2.1 Cables',
            },
        ),
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='setName!', max_length=128)),
                ('file', models.FileField(upload_to='')),
                ('filetype', models.CharField(blank=True, max_length=16)),
                ('uploaded', models.BooleanField(default=False)),
                ('generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='File', to='MSR.msrproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': '0 Transfer file',
                'verbose_name_plural': '0 Transfer files',
            },
        ),
    ]
