# Generated by Django 4.2.1 on 2023-05-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRVClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_type', models.CharField(choices=[('A', 'not defined'), ('B', 'Modbus TCP'), ('C', 'Modbus RTU'), ('D', 'BACnet')], default='A', max_length=2)),
                ('name', models.CharField(default='clients name', max_length=128)),
                ('controller', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Driver', to='MSR.msrcontroller', verbose_name='Controller')),
            ],
            options={
                'verbose_name': 'Z01 Driver-Client',
                'verbose_name_plural': 'Z01 Driver-Clients',
            },
        ),
    ]
